name: Deploy Next.js App

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the Node.js version required by your project

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
